#!/bin/bash


# Exercise 3 
# The goal is to create a shell script that add users 
# It will conform to linux program standard conventions.

FILE="/vagrant/stderr"

# Make sure the script is being executed with the super user privleges 
if [[ ${UID} -ne 0 ]]
then
	echo "The script must be executed using superuser privileges" 
	exit 1
fi

# If the user doesnt supply at least one argument, then give them help
NUMBE_OF_PARAMETERS="${#}"
if [[ NUMBE_OF_PARAMETERS -lt 1 ]]
then 
	echo "You supplied $NUMBE_OF_PARAMETERS arguments on the command" 
	echo "USAGE: ${0} USER_NAME [COMMENT] " 
	exit 1 
fi

# The first parameter is the user name 
USER_NAME=${1}
# The rest of the parameters are for the account comments 
shift 
COMMENT="${@}"
# Generate a password 
PASSWORD=$(date +%s%N | sha256sum | head -c48)

# Create the user with the password 
useradd -c "${COMMENT}" -m "${USER_NAME}" 
# Check to see if the sueradd command succeeded 
if [[ ${?} -ne 0 ]]
then 
	echo "The account could not be created. " 
	exit 1 
fi

# set the password 
echo ${PASSWORD} | passwd --stdin ${USER_NAME} 

# check to see if the passwd command succeeded
if [[ "${?}" -ne 0 ]]
then 
	echo "The passwod could not be created." 
	exit 1 
fi 

# Force password change on first login
passwd -e ${USER_NAME} 
# Display the username, password, and the host where the user was created. 

echo "Username : "
echo ${USER_NAME}
echo
echo "Password : "
echo ${PASSWORD}
echo 
echo "Hostname : "
echo ${HOSTNAME}